baseURL = "https://brettimkopf.github.io/Kacken-auf-Wacken"
staticDir = "static"
languageCode = 'de-de'
title = 'Kacken auf Wacken'
theme = "hello-friend-ng"



[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
#[services.googleAnalytics]
#  id = '' # G-MEASUREMENT_ID

[params]
  goToTop = true
  defaultColor = "light"
	enableThemeToggle = true
[menu]
[[menu.main]]
  pageRef="/"
  name = 'Startseite'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef="overview"
  name = 'Übersicht'
  url = 'overview/'
  weight = 20
[[menu.main]]
  pageRef="posts"
  name = 'Beiträge'
  url = 'posts/'
  weight = 30

[params.author]
  #avatar = "Titel.png"
  #intro = "Kacken auf Wacken"
  name = "BrettImKopf"

[params.footer]
  trademark = 2024
    
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "by <a href=\"https://github.com/BrettImKopf\">BrettImKopf</a>"
    ]



[[params.social]]
name = "github"
url = "https://github.com/BrettImKopf"

