baseURL = 'https://brettimkopf.github.io/Kacken-auf-Wacken/'
languageCode = 'de-de'
title = 'Kacken auf Wacken'
theme = "hugo-blog-awesome"



[services]
# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable Google Analytics, simply leave the field empty or remove the next two lines
[services.googleAnalytics]
  id = '' # G-MEASUREMENT_ID

[params]
  goToTop = true
  defaultColor = "light"

[menu]
[[menu.main]]
  pageRef="/"
  name = 'Startseite'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef="posts"
  name = 'Beiträge'
  url = '/posts/'
  weight = 20
[[menu.main]]
  name = 'Übersicht'
  url = '/overview/'
  weight = 30

[params.author]
  avatar = "Titel.png"
  intro = "Kacken auf Wacken"
  name = "BrettImKopf"
  description = "AAAEin kleines aber feines Kartenspiel über das Kacken auf Wacken. Check das!"




[[params.socialIcons]]
name = "github"
url = "https://github.com/BrettImKopf"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"