baseURL = ""https://brettimkopf.github.io/Kacken-auf-Wacken""
title        = "Kacken auf Wacken"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
 enableThemeToggle = true
  # Subtitle for home
  homeSubtitle = "Das Spiel"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Kacken auf Wacken Anleitung"
  keywords = "Wacken"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


  # And you can even create generic menu
  [[menu.main]]
    identifier = "main"
    name       = "Startseite"
    url        = "/"  
  
  [[menu.main]]
    identifier = "overview"
    name       = "Übersicht"
    url        = "overview/"
	
[params.author]
  #avatar = "Titel.png"
  #intro = "Kacken auf Wacken"
  name = "BrettImKopf"
	
	
	[params.footer]
  trademark = 2024
    
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "by <a href=\"https://github.com/BrettImKopf\">BrettImKopf</a>"
    ]