baseURL = "https://brettimkopf.github.io/Kacken-auf-Wacken/"
languageCode = "de-de"
title = "Kacken auf Wacken"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
subtitle = "Dies ist mein Untertitel"
[[menu.main]]
  identifier = "main"
  name = "Startseite"
  link = "#main"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "quickstart"
  name = "Quickstart"
  link = "#quickstart"
  url = "/quickstart"
  weight = 2
[[menu.main]]
  identifier = "introduction"
  name = "Einführung"
  link = "#introduction"
  url = "/introduction"
  weight = 3

[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials+FAQs"
  link = "#tutorials"
  url = "/tutorials"
  weight = 4
